console.log(true ? 1 : 2)
console.log(true ? 5 : 4)
console.log(false ? 'falso' : 'verdadeiro')
console.log(5 > 2 ? 'É sim' : 'É não')
console.log("Marcio" == "Marcio" ? "Olá, Marcio." : "Você não é o Marcio.")
console.log("Marcio" == "Mario" ? "Olá, Marcio." : "Você não é o Marcio.")
console.log()
console.log()
console.log()