console.log(5 > 3 && 3 == 2)
console.log(5 > 3 || 3 == 1)
console.log( 3 == 3 && "Marcio" == "Marcio")
console.log("Felipe" == "João" || false)
console.log(!true && true)
console.log(!(!(true && true)))
console.log()
console.log(true && true)
console.log(false || false)